/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_teskalabs_cvio_cviojni */

#ifndef _Included_com_teskalabs_cvio_cviojni
#define _Included_com_teskalabs_cvio_cviojni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_teskalabs_cvio_cviojni
 * Method:    jni_run
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_cvio_cviojni_jni_1run
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_teskalabs_cvio_cviojni
 * Method:    jni_shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_cvio_cviojni_jni_1shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_teskalabs_cvio_cviojni
 * Method:    jni_image_ready
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_teskalabs_cvio_cviojni_jni_1image_1ready
  (JNIEnv *, jclass);

/*
 * Class:     com_teskalabs_cvio_cviojni
 * Method:    jni_push_pixels_rgba_8888
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_cvio_cviojni_jni_1push_1pixels_1rgba_18888
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_teskalabs_cvio_cviojni
 * Method:    jni_push_pixels_rgba_565
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_cvio_cviojni_jni_1push_1pixels_1rgba_1565
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_teskalabs_cvio_cviojni
 * Method:    jni_set_delegate
 * Signature: (Lcom/teskalabs/cvio/VNCDelegate;)V
 */
JNIEXPORT void JNICALL Java_com_teskalabs_cvio_cviojni_jni_1set_1delegate
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
