/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_teskalabs_cvio_VNCServer */

#ifndef _Included_com_teskalabs_cvio_VNCServer
#define _Included_com_teskalabs_cvio_VNCServer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_teskalabs_cvio_VNCServer_BIND_ABOVE_CLIENT
#define com_teskalabs_cvio_VNCServer_BIND_ABOVE_CLIENT 8L
#undef com_teskalabs_cvio_VNCServer_BIND_ADJUST_WITH_ACTIVITY
#define com_teskalabs_cvio_VNCServer_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_teskalabs_cvio_VNCServer_BIND_ALLOW_OOM_MANAGEMENT
#define com_teskalabs_cvio_VNCServer_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_teskalabs_cvio_VNCServer_BIND_AUTO_CREATE
#define com_teskalabs_cvio_VNCServer_BIND_AUTO_CREATE 1L
#undef com_teskalabs_cvio_VNCServer_BIND_DEBUG_UNBIND
#define com_teskalabs_cvio_VNCServer_BIND_DEBUG_UNBIND 2L
#undef com_teskalabs_cvio_VNCServer_BIND_IMPORTANT
#define com_teskalabs_cvio_VNCServer_BIND_IMPORTANT 64L
#undef com_teskalabs_cvio_VNCServer_BIND_NOT_FOREGROUND
#define com_teskalabs_cvio_VNCServer_BIND_NOT_FOREGROUND 4L
#undef com_teskalabs_cvio_VNCServer_BIND_WAIVE_PRIORITY
#define com_teskalabs_cvio_VNCServer_BIND_WAIVE_PRIORITY 32L
#undef com_teskalabs_cvio_VNCServer_CONTEXT_IGNORE_SECURITY
#define com_teskalabs_cvio_VNCServer_CONTEXT_IGNORE_SECURITY 2L
#undef com_teskalabs_cvio_VNCServer_CONTEXT_INCLUDE_CODE
#define com_teskalabs_cvio_VNCServer_CONTEXT_INCLUDE_CODE 1L
#undef com_teskalabs_cvio_VNCServer_CONTEXT_RESTRICTED
#define com_teskalabs_cvio_VNCServer_CONTEXT_RESTRICTED 4L
#undef com_teskalabs_cvio_VNCServer_MODE_APPEND
#define com_teskalabs_cvio_VNCServer_MODE_APPEND 32768L
#undef com_teskalabs_cvio_VNCServer_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_teskalabs_cvio_VNCServer_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_teskalabs_cvio_VNCServer_MODE_MULTI_PROCESS
#define com_teskalabs_cvio_VNCServer_MODE_MULTI_PROCESS 4L
#undef com_teskalabs_cvio_VNCServer_MODE_PRIVATE
#define com_teskalabs_cvio_VNCServer_MODE_PRIVATE 0L
#undef com_teskalabs_cvio_VNCServer_MODE_WORLD_READABLE
#define com_teskalabs_cvio_VNCServer_MODE_WORLD_READABLE 1L
#undef com_teskalabs_cvio_VNCServer_MODE_WORLD_WRITEABLE
#define com_teskalabs_cvio_VNCServer_MODE_WORLD_WRITEABLE 2L
/*
 * Class:     com_teskalabs_cvio_VNCServer
 * Method:    jni_run
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_cvio_VNCServer_jni_1run
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_teskalabs_cvio_VNCServer
 * Method:    jni_shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_cvio_VNCServer_jni_1shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_teskalabs_cvio_VNCServer
 * Method:    jni_image_ready
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_teskalabs_cvio_VNCServer_jni_1image_1ready
  (JNIEnv *, jclass);

/*
 * Class:     com_teskalabs_cvio_VNCServer
 * Method:    jni_push_pixels_rgba_8888
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_cvio_VNCServer_jni_1push_1pixels_1rgba_18888
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_teskalabs_cvio_VNCServer
 * Method:    jni_push_pixels_rgba_565
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_cvio_VNCServer_jni_1push_1pixels_1rgba_1565
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_teskalabs_cvio_VNCServer
 * Method:    jni_set_delegate
 * Signature: (Lcom/teskalabs/cvio/VNCDelegate;)V
 */
JNIEXPORT void JNICALL Java_com_teskalabs_cvio_VNCServer_jni_1set_1delegate
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
